### ISSUE TITLE
Could not Unmarshal retirejsOutput (-n -p when package.json is not found)

### ISSUE THREAD

**Issue by rafaveira3** [globocom/huskyCI#233]
I have just found the cause of this issue:  when `-n -p` is being used and a repository does not have a package.json, the following exception comes from retire:
```
Exception caught:  { '0':
   { Error: ENOENT: no such file or directory, open './package.json'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
```

**Comment by rafaveira3** [comment]
Can't reproduce this anymore. Closing it for now.
